import { HeartHandshake, ShieldCheck, Sprout } from 'lucide-react';
import { brand, courses } from '../../content/site';
import { Action, Chapter, Reveal, Star, SunMark } from './Shared';

export const About = ({ onBook }) => <section id="about" className="about section-pad" aria-labelledby="about-title"><div className="page-width about-grid">
  <Reveal className="about-portrait"><div className="about-arch"><div className="about-arch-inner"/><SunMark size={140}/><span className="about-card-label" data-testid="about-card-label">A SPACE TO SIMPLY BE.</span><p data-testid="about-statement">You don’t need<br/>all the answers.<br/><em>Just a place<br/>to begin.</em></p><Star size={27}/><div className="handwritten" data-testid="about-signature">Bhavana</div></div><span className="portrait-caption" data-testid="about-art-caption">EMPATHY AT THE HEART. CLARITY IN THE CONVERSATION.</span></Reveal>
  <Reveal className="about-copy" delay={0.1}><Chapter number="03">THE HEART BEHIND MYSTIC TATTVA</Chapter><h2 id="about-title" className="display-title" data-testid="about-title">Hello, I’m <em>Bhavana.</em></h2><p className="eyebrow about-role" data-testid="about-role">TAROT READER · NUMEROLOGIST · LIFE COACH</p><p className="about-body" data-testid="about-biography">{brand.about}</p><p className="about-body" data-testid="about-approach">This isn’t about telling you what to do. It’s about helping you see your own possibilities, feel more connected to yourself, and find the courage for your next step.</p><div className="about-principles" data-testid="about-principles"><span><HeartHandshake size={19}/>Empathy, always</span><span><ShieldCheck size={19}/>Confidential by intention</span><span><Sprout size={19}/>Grounded in real life</span></div><Action variant="text" testId="about-book" onClick={() => onBook()}>Let’s find your way forward</Action></Reveal>
</div></section>;

export const Courses = ({ onBook }) => <section id="courses" className="courses section-pad" aria-labelledby="courses-title"><div className="page-width"><Reveal><Chapter number="04">FROM CURIOSITY TO CONNECTION</Chapter><div className="section-heading"><h2 className="display-title" id="courses-title" data-testid="courses-title">Learn with<br/><em>Mystic Tattva.</em></h2><div><p data-testid="courses-intro">Go beyond the reading. Begin a thoughtful relationship with tarot, one card at a time.</p><span className="preview-label" data-testid="courses-preview-label">COURSE PREVIEW · DETAILS COMING SOON</span></div></div></Reveal><div className="course-grid">{courses.map((course, i) => <Reveal className="course-card" delay={i * 0.07} key={course.id} data-testid={`course-${course.id}`}><div className="course-art" aria-hidden="true"><span>{course.roman}</span><div className="course-circle"/><Star size={26}/></div><span className="course-level" data-testid={`course-${course.id}-level`}>{course.level}</span><h3 data-testid={`course-${course.id}-title`}>{course.name}</h3><p data-testid={`course-${course.id}-description`}>{course.description}</p><Action variant="text" testId={`course-${course.id}-enquire`} onClick={() => onBook('Course Enquiry', `I’d like to learn more about the ${course.name}. Please share course details when available.`)}>Enquire Now</Action></Reveal>)}</div></div></section>;