import { useEffect, useState } from 'react';
import { Instagram, Facebook, Copy, Download, Check, Quote } from 'lucide-react';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '../ui/dialog';
import { Button } from '../ui/button';
import { toast } from 'sonner';
import { brand, disclaimer } from '../../content/site';
import { Action, Chapter, Reveal, Star, SunMark } from './Shared';

export const Testimonials = () => <section className="testimonials section-pad" aria-labelledby="testimonials-title"><div className="page-width"><Reveal><Chapter number="06">ROOM FOR YOUR REFLECTIONS</Chapter><div className="testimonials-heading"><h2 id="testimonials-title" className="display-title" data-testid="testimonials-title">Real journeys.<br/><em>Words that matter.</em></h2><p data-testid="testimonials-description">Every journey is personal. This space is reserved for genuine client reflections, shared with permission.</p></div></Reveal><div className="testimonial-grid">{['Finding clarity', 'Feeling heard', 'Moving forward'].map((title, i) => <Reveal delay={i * 0.05} className="testimonial-placeholder" key={title} data-testid={`testimonial-placeholder-${i}`}><Quote size={25} strokeWidth={1}/><h3 data-testid={`testimonial-title-${i}`}>{title}</h3><p data-testid={`testimonial-copy-${i}`}>A future space for an authentic client story.</p><span className="preview-label" data-testid={`testimonial-label-${i}`}>PLACEHOLDER · NOT A CLIENT REVIEW</span></Reveal>)}</div></div></section>;

export const Footer = ({ onDialog }) => <footer className="site-footer"><div className="page-width"><div className="footer-main"><div className="footer-brand"><a href="#home" className="brand" data-testid="footer-brand"><SunMark size={48}/><span>MYSTIC TATTVA<small>{brand.tagline}</small></span></a><p data-testid="footer-description">Ancient wisdom. A modern perspective.<br/>A journey that’s uniquely yours.</p><div className="social-links"><button aria-label="Instagram — profile coming soon" data-testid="social-instagram" onClick={() => onDialog({ type: 'social', platform: 'Instagram' })}><Instagram size={17}/></button><button aria-label="Facebook — profile coming soon" data-testid="social-facebook" onClick={() => onDialog({ type: 'social', platform: 'Facebook' })}><Facebook size={17}/></button><span data-testid="social-placeholder-label">SOCIALS COMING SOON</span></div></div><div className="footer-links"><h3 data-testid="footer-explore-title">EXPLORE</h3>{[['About Bhavana', 'about'], ['Signature Guidance', 'signature'], ['Courses', 'courses'], ['Shop', 'shop']].map(([text, id]) => <a key={id} href={`#${id}`} data-testid={`footer-${id}`}>{text}</a>)}</div><div className="footer-links"><h3 data-testid="footer-guidance-title">YOUR GUIDANCE</h3>{['Tarot Reading', 'Numerology', 'Life Coaching'].map((t, i) => <a key={t} href="#services" data-testid={`footer-service-${i}`}>{t}</a>)}<a href="#contact" data-testid="footer-contact">Get in Touch</a></div><div className="footer-closing"><Star size={32}/><p data-testid="footer-mantra">The answers begin<br/><em>with you.</em></p><a href="#home" data-testid="back-to-top">BACK TO THE TOP ↑</a></div></div><p className="footer-disclaimer" data-testid="footer-disclaimer">{disclaimer}</p><div className="footer-bottom"><span data-testid="copyright">© {new Date().getFullYear()} Mystic Tattva. All rights reserved.</span><div>{[['Privacy Policy', 'privacy'], ['Terms', 'terms'], ['Disclaimer', 'disclaimer']].map(([text, type]) => <button key={type} onClick={() => onDialog({ type })} data-testid={`footer-${type}`}>{text}</button>)}</div><span className="footer-love" data-testid="footer-love">MADE WITH INTENTION <Star size={12}/></span></div></div></footer>;

const legal = {
  privacy: { title: 'Privacy Policy', intro: 'A thoughtful approach to your information.', paragraphs: ['This Version 1 website prepares enquiry drafts in your browser. Form details are not sent to Mystic Tattva, saved in a database, or retained by the form after you leave or reload the page.', 'Copying or downloading an enquiry creates a copy under your control. Please avoid including sensitive medical, financial or personal information in your message. If you later share it through email or WhatsApp, that provider’s privacy terms also apply.', 'Public image and font providers, hosting infrastructure and preview-platform tools may process technical connection information under their own policies. A fuller privacy policy and a direct privacy contact will be added before live enquiry collection begins.'] },
  terms: { title: 'Terms', intro: 'A few things to know before you begin.', paragraphs: ['This website presents guidance services, planned courses and a sample product catalog. Preparing an enquiry does not create a booking, reserve a time slot, enrol you in a course, or place a product order.', 'All listed service prices are in Indian rupees. Session availability and final arrangements must be confirmed directly with Bhavana. Course details, product prices and stock availability are not yet published. Product photographs are illustrative, not photographs of confirmed inventory.', 'No payments are collected on this website. Full booking, cancellation and purchase terms will be provided before any paid service or purchase is confirmed. Spiritual guidance does not promise specific results; your choices remain your own.'] },
  disclaimer: { title: 'A note on guidance', intro: 'Insight, not certainty. Support, not a substitute.', paragraphs: [disclaimer, 'Readings and sessions are reflective and exploratory. No specific outcomes, predictions or supernatural effects are guaranteed. Decisions and actions remain your responsibility.', 'Crystals and spiritual products are offered for aesthetics, personal meaning and enjoyment. They are not medical treatments and are not claimed to diagnose, treat, cure or prevent any condition.'] },
};

export const SiteDialog = ({ dialog, onClose }) => {
  const [copied, setCopied] = useState(false);
  useEffect(() => setCopied(false), [dialog]);
  const copy = async () => { try { await navigator.clipboard.writeText(dialog.text); setCopied(true); } catch { toast.error('Copy isn’t available in this browser. Select the text below or download your draft.'); } };
  const download = () => { const url = URL.createObjectURL(new Blob([dialog.text], { type: 'text/plain;charset=utf-8' })); const a = document.createElement('a'); a.href = url; a.download = 'mystic-tattva-enquiry.txt'; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); };
  const isEnquiry = dialog?.type === 'enquiry';
  const policy = legal[dialog?.type];
  const title = isEnquiry ? 'Your enquiry is ready.' : policy?.title || (dialog?.type === 'whatsapp' ? 'A conversation, coming soon.' : `Meet us on ${dialog?.platform || 'social media'}.`);
  return <Dialog open={Boolean(dialog)} onOpenChange={(open) => { if (!open) onClose(); }}><DialogContent className="site-dialog" data-testid="site-dialog" data-lenis-prevent><SunMark size={48}/><DialogTitle className="dialog-title" data-testid="dialog-title">{title}</DialogTitle><DialogDescription className="dialog-description" data-testid="dialog-description">{isEnquiry ? 'This is your draft. Nothing has been sent, and no appointment has been booked.' : policy?.intro || 'Our official contact details are being prepared.'}</DialogDescription>
    {isEnquiry ? <><textarea className="enquiry-preview" readOnly value={dialog.text} aria-label="Your enquiry draft" data-testid="enquiry-preview" onFocus={(e) => e.target.select()}/><p className="dialog-note" data-testid="enquiry-not-sent">Save your message for now. Once our contact details are available, you can share it directly with Bhavana.</p><div className="dialog-actions"><Button className="action action-indigo" data-testid="copy-enquiry" onClick={copy}>{copied ? <Check size={16}/> : <Copy size={16}/>}<span aria-live="polite" data-testid="copy-status">{copied ? 'Copied to clipboard' : 'Copy enquiry'}</span></Button><Button className="action action-border" data-testid="download-enquiry" onClick={download}><Download size={16}/>Download draft</Button></div></> : policy ? <div className="legal-copy" data-testid={`${dialog.type}-content`}>{policy.paragraphs.map((p, i) => <p key={i}>{p}</p>)}</div> : <><p className="legal-copy" data-testid="contact-placeholder-copy">{dialog?.type === 'whatsapp' ? 'Bhavana’s WhatsApp number hasn’t been added yet. In the meantime, use the enquiry form to prepare a message you can copy or save. It will not be sent automatically.' : `The official Mystic Tattva ${dialog?.platform} profile will be linked here when it’s ready. Until then, explore our guidance or prepare an enquiry below.`}</p><Action variant="indigo" testId="placeholder-enquiry" onClick={() => { onClose(); setTimeout(() => { document.getElementById('contact')?.scrollIntoView({ behavior: window.matchMedia('(prefers-reduced-motion: reduce)').matches ? 'auto' : 'smooth' }); document.getElementById('name')?.focus({ preventScroll: true }); }, 80); }}>Prepare an enquiry instead</Action></>}
  </DialogContent></Dialog>;
};