import { ArrowUpRight, Clock3, Check } from 'lucide-react';
import { services, currency } from '../../content/site';
import { Action, Chapter, Reveal, ServiceSymbol, Star, SunMark } from './Shared';

export const Services = ({ onBook }) => <section id="services" className="services section-pad" aria-labelledby="services-title"><div className="page-width">
  <Reveal><Chapter number="01">YOUR INNER COMPASS</Chapter><div className="section-heading"><h2 id="services-title" className="display-title" data-testid="services-title">Clarity looks different<br/> <em>for everyone.</em></h2><p data-testid="services-intro">Wherever you are on your journey, there’s a space for you here. Choose the guidance that feels right.</p></div></Reveal>
  <div className="services-grid">{services.map((service, i) => <Reveal key={service.id} delay={i * 0.08} className={`service-card service-${service.id}`} data-testid={`service-${service.id}`}>
    <div className="service-top"><ServiceSymbol type={service.id}/><span className="card-number">/{service.number}</span></div>
    <h3 data-testid={`${service.id}-title`}>{service.name}</h3><p className="service-subtitle" data-testid={`${service.id}-subtitle`}>{service.subtitle}</p><p className="service-description" data-testid={`${service.id}-description`}>{service.description}</p>
    <div className="service-packages">{service.packages.length ? service.packages.map((pack, index) => <button key={pack.name} data-testid={`${service.id}-package-${index}`} className="package-row" onClick={() => onBook(service.name, `I’m interested in ${service.name} — ${pack.name} (${currency(pack.price)}).`)}><span>{pack.name}</span><strong>{currency(pack.price)}</strong><ArrowUpRight size={13}/></button>) : <div className="numerology-note" data-testid="numerology-pricing"><span className="number-pattern" aria-hidden="true">1 <i>·</i> 7 <i>·</i> 9</span><p>Your numbers. Your story.</p><ul className="numerology-topics"><li>Explore the symbolism of your numbers</li><li>Reflect on patterns and personal questions</li><li>Discuss the right session with Bhavana</li></ul><small>Personalised packages & pricing on enquiry.</small></div>}</div>
    <p className="package-note" data-testid={`${service.id}-monthly-note`}>{service.note}</p><Action testId={`${service.id}-enquire`} variant="text" onClick={() => onBook(service.name)}>Explore {service.name}</Action>
  </Reveal>)}</div>
  <Reveal className="services-footnote"><Star size={17}/><p data-testid="services-footnote">Not here to predict your life. Here to help you live it with intention.</p></Reveal>
</div></section>;

export const Signature = ({ onBook }) => <section id="signature" className="signature section-pad" aria-labelledby="signature-title"><div className="page-width signature-grid">
  <Reveal className="signature-art"><div className="signature-orbit"/><div className="signature-orbit second"/><div className="signature-tarot side-left"><span>THE PATTERNS</span><ServiceSymbol type="numerology"/><small>NUMEROLOGY</small></div><div className="signature-tarot side-right"><span>THE POSSIBILITY</span><ServiceSymbol type="coaching"/><small>LIFE COACHING</small></div><div className="signature-tarot center"><span>THE INNER COMPASS</span><SunMark size={120}/><Star size={21}/><small>TAROT</small><span className="tarot-bottom-line"/></div><Star className="signature-spark" size={42}/><span className="signature-art-caption" data-testid="signature-art-caption">THREE PERSPECTIVES. ONE BEAUTIFUL JOURNEY.</span></Reveal>
  <Reveal delay={0.12} className="signature-copy"><Chapter number="02" light>THE SIGNATURE EXPERIENCE</Chapter><p className="eyebrow signature-eyebrow" data-testid="signature-label">CONNECTED. CONSIDERED. COMPLETELY YOU.</p><h2 id="signature-title" className="display-title" data-testid="signature-title">Mystic Tattva<br/><em>Signature Guidance</em></h2><p className="signature-mantra" data-testid="signature-mantra">Understand your patterns.<br/>Explore your questions.<br/>Create your next steps.</p><p className="signature-description" data-testid="signature-description">One thoughtful session bringing together Numerology, Tarot Reading and Life Coaching. A fuller picture of you—and a grounded way forward.</p><div className="signature-includes" data-testid="signature-includes">{['Numerology', 'Tarot Reading', 'Life Coaching'].map(t => <span key={t}><Check size={12}/>{t}</span>)}</div><div className="signature-book"><div className="signature-price" data-testid="signature-price">{currency(2499)}<span><Clock3 size={13}/>90-minute session</span></div><Action testId="signature-book" onClick={() => onBook('Signature Guidance', 'I’m interested in Mystic Tattva Signature Guidance — 90 minutes (₹2,499).')}>Book Signature Guidance</Action></div></Reveal>
</div></section>;